Repository howroyd/simonsays, pull requests merged in 2023-11, with the labels that each got.

#54 Added look for newer version and display in console and gui if available
  pyproject.toml
  requirements.txt
  src/simonsays_drgreengiant/gui.py
  src/simonsays_drgreengiant/simonsays.py
Labels: enhancement, dependencies

#55 52 look and headbang smoothness
  pyproject.toml
  src/simonsays_drgreengiant/gameactions.py
  src/simonsays_drgreengiant/hidactions.py
  src/simonsays_drgreengiant/phasmoactions.py
Labels: enhancement

#57 New commands
  pyproject.toml
  src/simonsays_drgreengiant/phasmoactions.py
  src/simonsays_drgreengiant/simonsays.py
Labels: enhancement

#58 Added headshake and hurricane
  pyproject.toml
  src/simonsays_drgreengiant/phasmoactions.py
Labels: enhancement

#63 Update README.md
  README.md
Labels: documentation
